CREATE TABLE ARTICLE(
    ID INT(11) PRIMARY KEY, 
	REF INT(11), 
    DESIGNATION VARCHAR(255),
    PRIX DECIMAL(7,2),
    ID_FOU INT(11)
    );
    
CREATE TABLE FOURNISSEUR(
    ID INT(11) PRIMARY KEY,
    NOM VARCHAR(25)
    );
    
CREATE TABLE BON(
    ID INT(11) PRIMARY KEY,
    NUMERO INT(11),
    DATE_CMDE DATETIME DEFAULT CURRENT_TIMESTAMP,
    DELAI  INT(11),
    ID_FOU INT(11)
    );
    
 CREATE TABLE COMPO(
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    QTE INT(11),
    ID_ART INT(11),
    ID_BON INT(11)
     );
     
ALTER TABLE BON ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);

ALTER TABLE ARTICLE ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);

ALTER TABLE COMPO ADD CONSTRAINT FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID);
ALTER TABLE COMPO ADD CONSTRAINT FOREIGN KEY (ID_BON) REFERENCES BON(ID); 