CREATE TABLE ARTICLE(
    ID INT PRIMARY KEY, 
	REF INT(11), 
    DESIGNATION VARCHAR(100),
    PRIX INT(11),
    ID_FOU INT(11)UNIQUE
    );
    
CREATE TABLE FOURNISSEUR(
    ID INT PRIMARY KEY,
    NOM VARCHAR(100)
    );
    
CREATE TABLE BON(
    ID INT PRIMARY KEY,
    NUMERO INT(11),
    DATE_CMDE DATE DEFAULT CURRENT_TIMESTAMP,
    DELAI  INT(11),
    ID_FOU INT(11)UNIQUE
    );
    
 CREATE TABLE COMPO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    QTE INT(11),
    ID_ART INT(11)UNIQUE,
    ID_BON INT(11)UNIQUE
     );
     
ALTER TABLE BON ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);

ALTER TABLE ARTICLE ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);

ALTER TABLE COMPO ADD CONSTRAINT FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID);
ALTER TABLE COMPO ADD CONSTRAINT FOREIGN KEY (ID_BON) REFERENCES BON(ID); 