SELECT ARTICLE.*
FROM ARTICLE
WHERE PRIX >2.00;

SELECT ARTICLE.*
FROM ARTICLE
WHERE PRIX >=2.00 AND PRIX <=6.25;

SELECT ARTICLE.*
FROM ARTICLE
WHERE PRIX BETWEEN 2.00 AND 6.25;

SELECT ARTICLE.*
FROM ARTICLE
WHERE PRIX NOT BETWEEN 2.00 AND 6.25
AND ID_FOU = (SELECT ID FROM FOURNISSEUR WHERE NOM = 'Française d''Imports')
ORDER BY PRIX DESC;

SELECT ARTICLE.*
FROM ARTICLE
WHERE ID_FOU = (SELECT ID FROM FOURNISSEUR WHERE NOM = 'Française d''Imports')
OR ID_FOU = (SELECT ID FROM FOURNISSEUR WHERE NOM = 'Dubois et Fils');

SELECT ARTICLE.*
FROM ARTICLE
WHERE ID_FOU IN (SELECT ID FROM FOURNISSEUR WHERE NOM = 'Française d''Imports' OR NOM = 'Dubois et Fils');

SELECT ARTICLE.*
FROM ARTICLE
WHERE ID_FOU NOT IN (SELECT ID FROM FOURNISSEUR WHERE NOM IN ('Française d''Imports', 'Dubois et Fils'));

SELECT *
FROM BON
WHERE DATE_CMDE BETWEEN '2019-02-01' AND '2019-04-30';



