--a
SELECT *
FROM ARTICLE
ORDER BY DESIGNATION ASC;
--b
SELECT *
FROM ARTICLE
ORDER BY ARTICLE.PRIX DESC;
--c
SELECT *
FROM ARTICLE
WHERE DESIGNATION LIKE '%boulon%'
ORDER BY PRIX ASC;
--d
SELECT *
FROM ARTICLE
WHERE DESIGNATION LIKE '%sachet%';
--e
SELECT *
FROM ARTICLE
WHERE UPPER(DESIGNATION) LIKE'%SACHET%';
--f
SELECT ARTICLE.REF, FOURNISSEUR.NOM
FROM ARTICLE
JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
ORDER BY FOURNISSEUR.NOM ASC, PRIX DESC;

--g
SELECT *
FROM ARTICLE
JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE FOURNISSEUR.NOM = 'Dubois & Fils';
--h
SELECT FOURNISSEUR.NOM, AVG(ARTICLE.PRIX) AS PRIX_MOYEN
FROM ARTICLE
JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE FOURNISSEUR.NOM = 'Dubois & Fils';

---i
SELECT FOURNISSEUR.NOM, AVG(ARTICLE.PRIX) AS PRIX_MOYEN
FROM ARTICLE
JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
GROUP BY FOURNISSEUR.NOM
--j
SELECT *
FROM BON
WHERE DATE_CMDE BETWEEN '2019-03-01' AND DATE '2019-04-05 12:00:00';
--k
SELECT BON.ID, ARTICLE.DESIGNATION
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON
JOIN ARTICLE ON ARTICLE.ID = COMPO.ID_ART 
WHERE DESIGNATION LIKE '%Boulon%';

--l
SELECT  DISTINCT BON.ID, FOURNISSEUR.NOM
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON
JOIN ARTICLE ON ARTICLE.ID = COMPO.ID_ART 
JOIN FOURNISSEUR ON FOURNISSEUR.ID = ARTICLE.ID_FOU
WHERE DESIGNATION LIKE '%Boulon%';

--m

SELECT BON.ID, SUM(ARTICLE.PRIX * COMPO.QTE)
FROM BON 
JOIN COMPO ON BON.ID = COMPO.ID_BON
JOIN ARTICLE ON ARTICLE.ID = COMPO.ID_ART
GROUP BY BON.ID;

--n
SELECT BON.ID, SUM(COMPO.QTE) AS TOTAL_QTE
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON
GROUP BY BON.ID;

--o
SELECT BON.ID, SUM(COMPO.QTE) AS TOTAL_QTE
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON
GROUP BY BON.ID
HAVING TOTAL_QTE >  25;

--p
SELECT SUM(ARTICLE.PRIX * COMPO.QTE) AS MONTANT_TOTAL
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON 
JOIN ARTICLE ON ARTICLE.ID = COMPO.ID_ART
WHERE MONTH(DATE_CMDE)=4;

--a

SELECT A1.DESIGNATION, A1.ID_FOU AS Fournisseur_1, A2.ID_FOU AS Fournisseur_2
FROM ARTICLE A1
JOIN ARTICLE A2 ON A1.DESIGNATION = A2.DESIGNATION 
AND A1.ID_FOU <> A2.ID_FOU;


